### ISSUE TITLE
dApp UI - Token staking experience 

### ISSUE THREAD

**Issue by danielssonn** [danielssonn/blockchain-oracles#34]
Number of transactions occur in the staking flow. We need UI to let the user know what steps are taking place, vs. just wallet transactions popping.

- The UI updates first with the token debit, before even the first staking transaction happens. The UI need to update last and only if all staking has been approved by the user and transactions went through.

**Comment by rccrc** [comment]
5787c79bb885818fab7a1f3ac1379c700da170d7 update after staking complete
