### ISSUE TITLE
dApp UI - Staking amount digits

### ISSUE THREAD

**Issue by danielssonn** [danielssonn/blockchain-oracles#35]
The number of tokens in the app and in the wallet has to look the same. The wallet shows 'whole tokens' 10**18, while the wallet asks to approve 18 decimal values

**Comment by rccrc** [comment]
try token * (10 ** 18) got overflown error

**Comment by danielssonn** [comment]
> 

That overflow is a javascript number issue creating BigNumbers for ethers. Use something like this:  web3.utils.toBN(amount*(10**18))
